In [5]:
# Import Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# Load and Read in CSV Squirrel Data
squirrel_df = pd.read_csv('Resources/nyc_squirrels_2.csv')  
squirrel_df = squirrel_df.loc[:, ~squirrel_df.columns.str.contains('^Unnamed')]
squirrel_df

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,highlight_fur_color,...,approaches,indifferent,runs_from,other_interactions,lat_long,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581),NaN,19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755),NaN,19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163),NaN,19,4,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466),NaN,19,4,19,13
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973),NaN,19,4,19,13
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883),NaN,19,4,19,13
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912),NaN,19,4,19,13
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025),NaN,19,4,19,13

In [10]:
#duplicateRows = squirrel_df[squirrel_df.duplicated()]
ids = squirrel_df["unique_squirrel_id"]
duplicates = squirrel_df[ids.isin(ids[ids.duplicated()])].sort_values("unique_squirrel_id")
duplicates
# 5 Rows identifed as duplicates. Drop to arrive at accurate counts.

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,highlight_fur_color,...,approaches,indifferent,runs_from,other_interactions,lat_long,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
2532,-73.976620,40.766191,1F-AM-1010-04,01F,AM,10102018,4,Adult,Gray,NaN,...,False,True,False,NaN,POINT (-73.9766195697096 40.7661907261547),NaN,19,4,19,13
2613,-73.976588,40.766095,1F-AM-1010-04,01F,AM,10102018,4,Adult,Gray,NaN,...,False,True,False,NaN,POINT (-73.9765877920583 40.7660946071574),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2271,-73.956967,40.794879,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9569670900695 40.794879285681304),NaN,19,4,19,13
1539,-73.957711,40.798406,40B-AM-1019-06,40B,AM,10192018,6,Juvenile,Gray,White,...,False,False,True,NaN,POINT (-73.957710975899 40.7984055614047),NaN,19,4,19,13
2167,-73.958236,40.798775,40B-AM-1019-06,40B,AM,10192018,6,Juvenile,Gray,White,...,False,False,True,NaN,POINT (-73.9582363437135 40.7987752300505),NaN,19,4,19,13
2106,-73.977262,40.769282,4C-PM-1010-05,04C,PM,10102018,5,Adult,Gray,Cinnamon,...,False,False,False,NaN,POINT (-73.9772624834791 40.7692821918543),NaN,19,4,19,13
2888,-73.977165,40.769305,4C-PM-1010-05,04C,PM,10102018,5,Adult,Gray,Cinnamon,...,False,False,False,NaN,POINT (-73.9771646835311 40.7693049165084),NaN,19,4,19,13
519,-73.974945,40.772066,7D-PM-1010-01,07D,PM,10102018,1,Adult,Gray,White,...,False,False,False,NaN,POINT (-73.9749446629706 40.7720659696067),NaN,19,4,19,13
2234,-73.974852,40.771959,7D-PM-1010-01,07D,PM,10102018,1,Adult,Gray,White,...,False,False,False,NaN,POINT (-73.9748522796455 40.7719586621003),NaN,19,4,19,13

In [11]:
# Remove duplicate squirrel observations
squirrel_df = squirrel_df.drop_duplicates(subset=['unique_squirrel_id'])
squirrel_df

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,highlight_fur_color,...,approaches,indifferent,runs_from,other_interactions,lat_long,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581),NaN,19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755),NaN,19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163),NaN,19,4,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,NaN,...,False,False,True,NaN,POINT (-73.9639431360458 40.7908677445466),NaN,19,4,19,13
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,White,...,False,True,False,NaN,POINT (-73.9704015859639 40.7825600069973),NaN,19,4,19,13
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Black, Cinnamon, White",...,False,True,False,NaN,POINT (-73.9665871993517 40.7836775064883),NaN,19,4,19,13
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Cinnamon, White",...,False,True,False,NaN,POINT (-73.9639941227864 40.7899152327912),NaN,19,4,19,13
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Gray, White",...,True,False,False,NaN,POINT (-73.9754794191553 40.7696404489025),NaN,19,4,19,13

In [ ]:
# Convert all booleans to 0s and 1s 
# squirrel_df = squirrel_df.applymap(lambda x: 1 if x == True else x)
# squirrel_df = squirrel_df.applymap(lambda x: 0 if x == False else x)
# squirrel_df

In [12]:
# Check for duplicates again
ids = squirrel_df["unique_squirrel_id"]
duplicates = squirrel_df[ids.isin(ids[ids.duplicated()])].sort_values("unique_squirrel_id")
duplicates

Empty DataFrame
Columns: [long, lat, unique_squirrel_id, hectare, shift, date, hectare_squirrel_number, age, primary_fur_color, highlight_fur_color, combination_of_primary_and_highlight_color, color_notes, location, above_ground_sighter_measurement, specific_location, running, chasing, climbing, eating, foraging, other_activities, kuks, quaas, moans, tail_flags, tail_twitches, approaches, indifferent, runs_from, other_interactions, lat_long, zip_codes, community_districts, borough_boundaries, city_council_districts, police_precincts]
Index: []

[0 rows x 36 columns]

In [13]:
# Calculate total of each color type
gray_sq = squirrel_df[squirrel_df["primary_fur_color"] == "Gray"]
gray_sq_count = len(squirrel_df[squirrel_df["primary_fur_color"] == "Gray"])
cinnamon_sq_count = len(squirrel_df[squirrel_df["primary_fur_color"] == "Cinnamon"])
black_sq_count = len(squirrel_df[squirrel_df["primary_fur_color"] == "Black"])
print(gray_sq_count)
print(cinnamon_sq_count)
print(black_sq_count)

2468
392
103

In [14]:
# Calculate percentage of each squirrel type
gray_percent = len(squirrel_df[squirrel_df["primary_fur_color"] == "Gray"])/(squirrel_df['primary_fur_color'].count()) * 100
cinnamon_percent = len(squirrel_df[squirrel_df["primary_fur_color"] == "Cinnamon"])/(squirrel_df['primary_fur_color'].count()) * 100
black_percent = len(squirrel_df[squirrel_df["primary_fur_color"] == "Black"])/(squirrel_df['primary_fur_color'].count()) * 100
print(gray_percent)
print(cinnamon_percent)
print(black_percent)

83.29395882551468
13.229834627067161
3.476206547418157